---
- name: update web servers
  hosts: production
  remote_user: root
  tasks:
    - name: ensure apache is latest version
      yum: 
        name: httpd
        state: latest
    - name: write the apache config file
      template:
        src: /srv/https.j2
        dest: /etc/httpd.conf
